[package]
name = "genetic-algorithms"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "*", features = ["derive"] }
rand = "*"
itertools = "*"
color-eyre = "*"
crossterm = "*"
ratatui = "*"
